name: create-chirp-executable

on:
  push:
      tags:
        - 'v[0-9]+,[0-9]+,[0-9]+'
      branches:  
        - main 
  workflow_dispatch:


jobs:
  publish: 

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: |
        cd src/Chirp.CLI
        dotnet restore
        cd ../..
        cd src/SimpleDB
        dotnet restore

    - name: Build
      run: |
        cd src/Chirp.CLI
        dotnet build  --configuration Release --no-restore

    - name: Test
      run: |
        cd test/Chirp.CLI.Client.Tests
        dotnet test --no-restore --verbosity normal
        cd ../..
        cd test/Chirp.CSVDB.Tests
        dotnet test --no-restore --verbosity normal

        
    - name: Get current tag name
      id: tag
      run: echo ::set-output name=TAG::$(git describe --tags --abbrev=0)
        
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: "src/Chirp.CLI/Program.cs"
        tag_name: 1.0.1
        token: ${{ secrets.GITHUB_TOKEN }}


   
