name: create-chirp-executable

on:
  push:
      tags:
        - 'v[0-9]+,[0-9]+,[0-9]+'
      branches:  
        - main 
  workflow_dispatch:


jobs:
  publish: 

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: |
        cd src/Chirp.CLI
        dotnet restore
        cd ../..
        cd src/SimpleDB
        dotnet restore

    - name: Build
      run: |
        cd src/Chirp.CLI
        dotnet build  --configuration Release --no-restore
        cd ../..
        dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime "linux-x64" -c Release -o "release linux-64"
        dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime "win-x64" -c Release -o "release Windows-64"
        dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime "osx-x64" -c Release -o "release macos-64"
        dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --runtime "osx-arm64" -c Release -o "release macos-arm64"

        7z a -tzip "Linux-64.zip" "./Linux-64/*"
        7z a -tzip "Windows-64.zip" "./Windows-64/*"
        7z a -tzip "macos-64.zip" "./macos-64/*"
        7z a -tzip "macos-arm64.zip" "./macos-arm64/*"


    - name: Test
      run: |
        cd test/Chirp.CLI.Client.Tests
        dotnet test --no-restore --verbosity normal
        cd ../..
        cd test/Chirp.CSVDB.Tests
        dotnet test --no-restore --verbosity normal
        
    - name: Get current tag name
      id: tag
      run: echo ::set-output name=TAG::$(git describe --tags --abbrev=0)
        
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: |
          "Linux-64*"
          "Windows-64*"
          "macos-64*"
          "macos-arm64*"
        tag_name: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}


   
