name: create-chirp-executable

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - NewExecutable
  workflow_dispatch:

jobs:
  publish:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: |
          cd src/Chirp.Web
          dotnet restore

      # - name: Test
      #   run: |
      #     cd test/razorwebApp_test/Integration_test.cs
      #     dotnet test --no-restore --verbosity normal
      #     cd ../..
      #     cd test/razorwebApp_test/UnitTest.cs
      #     dotnet test --no-restore --verbosity normal

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "TAG=$latest_tag" >> $GITHUB_ENV

      - name: Set Release Name
        id: release_name
        run: echo "RELEASE_NAME=${{ env.TAG }}" >> $GITHUB_ENV

      - name: Build
        run: |

          release_linux="Chirp-${{ github.ref_name }}-linux"
          release_windows="Chirp-${{ github.ref_name }}-windows"
          release_macos="Chirp-${{ github.ref_name }}-macos"
          release_macos_arm="Chirp-${{ github.ref_name }}-macos_arm"

          cd src/Chirp.Web
          dotnet build --configuration Release --no-restore
          cd ../..

          dotnet publish src/Chirp.Web/Chirp.Web.csproj --framework net7.0 --runtime "linux-x64" -c Release -o "$release_linux" -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:PublishTrimmed=true
          dotnet publish src/Chirp.Web/Chirp.Web.csproj --framework net7.0 --runtime "win-x64" -c Release -o "$release_windows" -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:PublishTrimmed=true
          dotnet publish src/Chirp.Web/Chirp.Web.csproj --framework net7.0 --runtime "osx-x64" -c Release -o "$release_macos" -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:PublishTrimmed=true
          dotnet publish src/Chirp.Web/Chirp.Web.csproj --framework net7.0 --runtime "osx-arm64" -c Release -o "$release_macos_arm" -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:PublishTrimmed=true

          7z a -tzip "Chirp-linux-64.zip" "./${release_linux}/*"
          7z a -tzip "Chirp-windows-64.zip" "./${release_windows}/*"
          7z a -tzip "Chirp-macos-64.zip" "./${release_macos}/*"
          7z a -tzip "Chirp-macos-arm64.zip" "./${release_macos_arm}/*"

          rm -r "$release_linux"
          rm -r "$release_windows"
          rm -r "$release_macos"
          rm -r "$release_macos_arm"

      - name: Publish release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.RELEASE_NAME }}
          files: "Chirp*"
