name: Generate PDF from Markdown

on:
  push:
    branches:
      - raport

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Pandoc and TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive

      - name: Convert Markdown to PDF
        run: |
          cd docs
          pandoc report.md -o report.pdf

      - name: Commit PDF
        run: |
          git config --global user.name 'Silas Wolff'
          git config --global user.email 'siwo@itu.dk'
          git add docs/report.pdf
          git commit -m "Generate PDF"
          git push

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: Generated PDF
          path: docs/report.pdf
